DROP table IF EXISTS `#__ddc_coupons`;
DROP table IF EXISTS `#__ddc_countries`
DROP table IF EXISTS `#__ddc_currencies`
DROP table IF EXISTS `#__ddc_images`;
DROP table IF EXISTS `#__ddc_orders`;
DROP table IF EXISTS `#__ddc_order_histories`;
DROP table IF EXISTS `#__ddc_order_items`;
DROP table IF EXISTS `#__ddc_order_calc_rules`;
DROP table IF EXISTS `#__ddc_orderstates`;
DROP table IF EXISTS `#__ddc_products`;
DROP table IF EXISTS `#__ddc_product_prices`;
DROP table IF EXISTS `#__ddc_shoppingcart_headers`;
DROP table IF EXISTS `#__ddc_shoppingcart_details`;
DROP table IF EXISTS `#__ddc_vendors`;
DROP table IF EXISTS `#__ddc_user_vendor`;
